version: '3.8'

services:
  # MariaDB-Datenbank
  db:
    image: mariadb:10.6
    container_name: kinderrechte_db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: drupal
      MARIADB_USER: drupal
      MARIADB_PASSWORD: drupalpass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - drupal_network

  # Drupal-Webserver
  drupal:
    build: .
    image: drupal:10-apache
    container_name: kinderrechte_drupal
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - drupal_modules:/var/www/html/modules
      - drupal_profiles:/var/www/html/profiles
      - drupal_themes:/var/www/html/themes
      - drupal_sites:/var/www/html/sites
      - ./config:/var/www/config
    environment:
      DRUPAL_DATABASE_HOST: db
      DRUPAL_DATABASE_PORT: 3306
      DRUPAL_DATABASE_NAME: drupal
      DRUPAL_DATABASE_USERNAME: drupal
      DRUPAL_DATABASE_PASSWORD: drupalpass
      PHP_FPM_CLEAR_ENV: "no"
    networks:
      - drupal_network

  # Adminer für Datenbankmanagement
  adminer:
    image: adminer:latest
    container_name: kinderrechte_adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      ADMINER_DEFAULT_SERVER: db
    networks:
      - drupal_network

networks:
  drupal_network:
    driver: bridge

volumes:
  db_data:
  drupal_modules:
  drupal_profiles:
  drupal_themes:
  drupal_sites: